name: Build binaries for distribution

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  assemble:
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang, g++]
    runs-on: ubuntu-24.04
    container: ubuntu:rolling
    steps:
      - name: Install deps
        run: |
          apt update && apt upgrade -y
          apt install -y cmake build-essential make git
          apt install -y ${{ matrix.compiler }}
      - uses: actions/checkout@main
      - name: Fix git ownership
        run: |
          git config --global --add safe.directory $(pwd)
      - name: Print environment
        run: |
          cmake --version
      - name: Run build
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j $(nproc)
      - name: Assemble dist files
        run: |
          mkdir dist
          mkdir dist/bin

          mkdir dist/share
          mkdir dist/share/umbra

          cp build/bin/umbra dist/bin
          cp -r share dist/
      - name: Compress distribution
        run: |
          tar -cvzf umbra.tar.gz dist/*
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: umbra.tar.gz
          asset_name: umbra-linux-x64.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
