name: Build docs

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: false

jobs:
  deploy:
    # Violet requires a version of GCC not yet offered by ubuntu 24 (which is ubuntu-latest),
    # so we need to use ubuntu:latest, which paradoxically is newer than
    # ubuntu-latest. 
    # GitHub Actions, brought to you by Microslop
    runs-on: ubuntu-24.04
    container: ubuntu:latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Install deps
        run: |
          apt update && apt upgrade -y
          apt install -y gcc build-essential make git libssl-dev libcurl4-openssl-dev
      - uses: actions/checkout@main
      - name: Fix git ownership
        run: |
          git config --global --add safe.directory $(pwd)
      - uses: LunarWatcher/install-violet@master
      - name: "Build page"
        run: |
          cd docs
          violet generate
      - uses: actions/configure-pages@v6
      - uses: actions/upload-pages-artifact@v5
        with:
          path: 'docs/pages'
      - uses: actions/deploy-pages@v5
        id: deployment
