name: Test workflow
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        - compiler: clang
          cxx: clang++
          cc: clang
        - compiler: g++
          cxx: g++
          cc: gcc
    runs-on: ubuntu-24.04
    container: ubuntu:rolling
    steps:
      - name: Install deps
        run: |
          apt update && apt upgrade -y
          apt install -y cmake build-essential make git
          apt install -y ${{ matrix.compiler }}

      - name: Environment information
        run: |
          ${{ matrix.compiler }} -v
      - uses: actions/checkout@main
      - name: Fix git ownership
        run: |
          git config --global --add safe.directory $(pwd)
      - name: Print environment
        run: |
          cmake --version
      - name: Run build
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j $(nproc)
        env:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}
      - name: Run test
        run: |
          cd build
          make -j $(nproc) test
        env:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}
  lint:
    runs-on: ubuntu-24.04
    container: ubuntu:rolling
    steps:
      - name: Install deps
        run: |
          apt update && apt upgrade -y
          apt install -y cmake gcc build-essential make git clang-tidy
      - uses: actions/checkout@main
      - name: Fix git ownership
        run: |
          git config --global --add safe.directory $(pwd)
      - name: Print environment
        run: |
          cmake --version
      - name: Lint
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DUMBRA_LINT=ON -DUMBRA_LINT_WARNINGS_ARE_ERRORS=ON
          make -j $(nproc)
